name: Auto Checkin

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      ACCOUNT1_EMAIL: ${{ secrets.ACCOUNT1_EMAIL }}
      ACCOUNT1_PASSWORD: ${{ secrets.ACCOUNT1_PASSWORD }}
      ACCOUNT2_EMAIL: ${{ secrets.ACCOUNT2_EMAIL }}
      ACCOUNT2_PASSWORD: ${{ secrets.ACCOUNT2_PASSWORD }}
      ACCOUNT3_EMAIL: ${{ secrets.ACCOUNT3_EMAIL }}
      ACCOUNT3_PASSWORD: ${{ secrets.ACCOUNT3_PASSWORD }}
      ACCOUNT4_EMAIL: ${{ secrets.ACCOUNT4_EMAIL }}
      ACCOUNT4_PASSWORD: ${{ secrets.ACCOUNT4_PASSWORD }}
      SERVER_KEY: ${{ secrets.SERVER_KEY }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - run: python checkin.py
