name: Auto Checkin

on:
  schedule:
    - cron: "8 16 * * *"  # 
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # 账号1
      ACCOUNT1_EMAIL: ${{ secrets.ACCOUNT1_EMAIL }}
      ACCOUNT1_PASSWORD: ${{ secrets.ACCOUNT1_PASSWORD }}
      # 账号2（如果有）
      ACCOUNT2_EMAIL: ${{ secrets.ACCOUNT2_EMAIL }}
      ACCOUNT2_PASSWORD: ${{ secrets.ACCOUNT2_PASSWORD }}
      # 账号2（如果有）
      ACCOUNT3_EMAIL: ${{ secrets.ACCOUNT3_EMAIL }}
      ACCOUNT3_PASSWORD: ${{ secrets.ACCOUNT3_PASSWORD }}
      # Server酱
      SERVER_KEY: ${{ secrets.SERVER_KEY }}
      # 消除Node.js警告
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - run: python checkin.py
