name: Auto Checkin

on:
  schedule:
    - cron: "*/15 * * * *"  # 每天北京时间 10:00 自动运行
  workflow_dispatch:     # 允许手动点击运行

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Run Checkin
        run: python checkin.py
